### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by emthompson-usgs** [conda-forge/gmprocess-feedstock#73]
Hi, @conda-forge/core I would like to request that we archive this repository. We (the developers of gmprocess) are not able to maintain the conda distribution. Thanks.

**Comment by beckermr** [comment]
Thanks @ocefpaf!

**Comment by jakirkham** [comment]
Oh ok. Sorry for the disruption then

**Comment by ocefpaf** [comment]
> I think that we would need to turn all of those into conda packages and maintain them as well, and this just seemed overwhelming.

With grayskull and the bot that is much easier nowadays. I literally just created most of the `esi-` in a few minutes in https://github.com/conda-forge/staged-recipes/pull/21198

**Comment by emthompson-usgs** [comment]
Okay, great to know. Thank you!

**Comment by mhearne-usgs** [comment]
@ocefpaf Also note that the gmprocess source repository has moved to a gitlab instance here:

https://code.usgs.gov/ghsc/esi/groundmotion-processing

**Comment by emthompson-usgs** [comment]
@mhearne-usgs I did update that in the most recent PR [here](https://github.com/conda-forge/gmprocess-feedstock/pull/72/files). And it looks to me like @ocefpaf is working with that PR and so it should be good.

**Comment by ocefpaf** [comment]
> @ocefpaf Also note that the gmprocess source repository has moved to a gitlab instance here:

The beauty of grayskull is that, if this metadata update is in the PyPI published package, we will get it here too,
